import type { Metadata } from 'next';
import { Inter, Instrument_Sans, Tinos } from 'next/font/google';
import 'modern-normalize';
import './globals.css';
import Header from '@/components/Header/Header';

const interSans = Inter({
  variable: '--font-inter-sans',
  weight: ['900', '800', '700', '600', '500', '400', '300'],
  style: ['normal', 'italic'],
  subsets: ['latin', 'cyrillic'],
  display: 'swap',
});

const instrumentSans = Instrument_Sans({
  variable: '--font-instrument-sans',
  weight: ['600'],
  subsets: ['latin'],
  display: 'swap',
});

const tinosSans = Tinos({
  variable: '--font-tinos-sans',
  weight: ['400'],
  subsets: ['latin', 'cyrillic'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk">
      <body
        className={`${interSans.variable} ${instrumentSans.variable} ${tinosSans.variable}`}
      >
        <Header />
        <main className="container">{children}</main>
      </body>
    </html>
  );
}
